# Generated by Django 3.2.9 on 2021-12-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_auto_20211223_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='author',
        ),
    ]
