# Generated by Django 3.2.9 on 2021-12-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_remove_userpost_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-created_on']},
        ),
    ]
